"""Placeholder cohort stubs used only when neither real OASIS pipeline outputs
nor synthetic cohort data are present yet, so the API demos out of the box.

When data/processed/risk_scores.json exists it is preferred; when a synthetic
cohort exists it is preferred; only when neither exist does this fallback kick in.
"""
from __future__ import annotations

MOCK_PATIENTS: list[dict] = [
    {
        "id": "PTID-1024",
        "age": 78,
        "sex": "F",
        "education_years": 12,
        "family_history": True,
        "comorbidities": ["Hypertension", "Type 2 diabetes"],
        "cognitive": {"scale": "MoCA", "latest": 17, "prior": 22, "months": 6},
        "blood": None,
        "imaging": None,
        "pet": None,
        "score": 0.87,
        "stage": 1,
        "factors": [
            {"text": "MoCA declined 5 points in 6 months", "effect": 0.32},
            {"text": "Age 78", "effect": 0.14},
            {"text": "Hypertension", "effect": 0.09},
            {"text": "Type 2 diabetes", "effect": 0.06},
            {"text": "Higher education (12 yrs)", "effect": -0.08},
        ],
        "updated_at": "2026-08-22 09:15",
        "history": [
            {"at": "2026-08-22 09:15", "text": "Risk-scored 0.87 → prioritized High at Stage 1"},
            {"at": "2026-07-10 11:02", "text": "Ingested from ADNI record, harmonized to shared schema"},
        ],
    },
    {
        "id": "PTID-1088",
        "age": 74,
        "sex": "M",
        "education_years": 16,
        "family_history": False,
        "comorbidities": ["Hypertension"],
        "cognitive": {"scale": "MoCA", "latest": 22, "prior": 24, "months": 6},
        "blood": None,
        "imaging": None,
        "pet": None,
        "score": 0.61,
        "stage": 1,
        "factors": [
            {"text": "MoCA declined 2 points in 6 months", "effect": 0.12},
            {"text": "Hypertension", "effect": 0.07},
            {"text": "Age 74", "effect": 0.08},
            {"text": "Higher education (16 yrs)", "effect": -0.14},
        ],
        "updated_at": "2026-08-21 16:40",
        "history": [
            {"at": "2026-08-21 16:40", "text": "Risk-scored 0.61 → prioritized Medium at Stage 1"},
            {"at": "2026-07-09 09:30", "text": "Ingested from ADNI record, harmonized to shared schema"},
        ],
    },
    {
        "id": "PTID-1102",
        "age": 81,
        "sex": "F",
        "education_years": 10,
        "family_history": False,
        "comorbidities": ["Hypertension", "Cardiovascular disease"],
        "cognitive": {"scale": "MoCA", "latest": 19, "prior": 23, "months": 6},
        "blood": {"pTau181": 4.8, "abeta4240": 0.052, "note": "Elevated p-tau181; Aβ42/40 ratio below reference range"},
        "imaging": None,
        "pet": None,
        "score": 0.92,
        "stage": 2,
        "factors": [
            {"text": "Elevated p-tau181 (4.8 pg/mL)", "effect": 0.22},
            {"text": "MoCA declined 4 points in 6 months", "effect": 0.18},
            {"text": "Low Aβ42/40 ratio (0.052)", "effect": 0.11},
            {"text": "Age 81", "effect": 0.09},
            {"text": "Higher education (10 yrs)", "effect": -0.05},
        ],
        "updated_at": "2026-08-22 14:05",
        "history": [
            {"at": "2026-08-22 14:05", "text": "Blood panel returned — p-tau181 elevated, advanced to Stage 2"},
            {"at": "2026-08-15 10:20", "text": "Risk-scored 0.92 → prioritized High at Stage 1"},
        ],
    },
    {
        "id": "PTID-1137",
        "age": 69,
        "sex": "M",
        "education_years": 18,
        "family_history": False,
        "comorbidities": [],
        "cognitive": {"scale": "MoCA", "latest": 28, "prior": 28, "months": 6},
        "blood": None,
        "imaging": None,
        "pet": None,
        "score": 0.34,
        "stage": 1,
        "factors": [
            {"text": "Higher education (18 yrs)", "effect": -0.18},
            {"text": "No comorbidity flags", "effect": -0.12},
            {"text": "MoCA stable at 28 over 6 months", "effect": -0.06},
            {"text": "Age 69", "effect": 0.04},
        ],
        "updated_at": "2026-08-20 11:12",
        "history": [
            {"at": "2026-08-20 11:12", "text": "Risk-scored 0.34 → prioritized Low at Stage 1"},
        ],
    },
    {
        "id": "PTID-1156",
        "age": 76,
        "sex": "F",
        "education_years": 14,
        "family_history": True,
        "comorbidities": ["Hypertension"],
        "cognitive": {"scale": "MoCA", "latest": 18, "prior": 20, "months": 6},
        "blood": {"pTau181": 2.9, "abeta4240": 0.085, "note": "Borderline p-tau181; Aβ42/40 ratio at lower reference"},
        "imaging": {"hippocampalVolumeCm3": 2.1, "note": "<5th percentile for age"},
        "pet": None,
        "score": 0.74,
        "stage": 3,
        "factors": [
            {"text": "Low hippocampal volume (2.1 cm³, <5th pct)", "effect": 0.26},
            {"text": "Borderline p-tau181 (2.9 pg/mL)", "effect": 0.10},
            {"text": "MoCA declined 2 points in 6 months", "effect": 0.09},
            {"text": "Age 76", "effect": 0.06},
            {"text": "Higher education (14 yrs)", "effect": -0.06},
        ],
        "updated_at": "2026-08-22 17:33",
        "history": [
            {"at": "2026-08-22 17:33", "text": "MRI shows low hippocampal volume → recommended PET"},
            {"at": "2026-08-11 12:01", "text": "Risk-scored 0.74 → prioritized High at Stage 2"},
        ],
    },
    {
        "id": "PTID-1171",
        "age": 72,
        "sex": "M",
        "education_years": 15,
        "family_history": False,
        "comorbidities": ["Type 2 diabetes"],
        "cognitive": {"scale": "MoCA", "latest": 23, "prior": 25, "months": 6},
        "blood": {"pTau181": 2.2, "abeta4240": 0.11, "note": "p-tau181 within reference; Aβ42/40 ratio normal"},
        "imaging": None,
        "pet": None,
        "score": 0.47,
        "stage": 2,
        "factors": [
            {"text": "Type 2 diabetes", "effect": 0.09},
            {"text": "Elevated p-tau181 (2.2 pg/mL)", "effect": 0.07},
            {"text": "MoCA declined 2 points in 6 months", "effect": 0.06},
            {"text": "Age 72", "effect": 0.05},
            {"text": "Higher education (15 yrs)", "effect": -0.12},
        ],
        "updated_at": "2026-08-19 15:26",
        "history": [
            {"at": "2026-08-19 15:26", "text": "Blood panel returned — within reference, staying Medium at Stage 2"},
            {"at": "2026-08-08 09:45", "text": "Risk-scored 0.47 → prioritized Medium at Stage 1"},
        ],
    },
    {
        "id": "PTID-1190",
        "age": 79,
        "sex": "F",
        "education_years": 9,
        "family_history": True,
        "comorbidities": ["Hypertension", "Type 2 diabetes", "Cardiovascular disease"],
        "cognitive": {"scale": "MoCA", "latest": 15, "prior": 20, "months": 6},
        "blood": {"pTau181": 6.1, "abeta4240": 0.041, "note": "Markedly elevated p-tau181; Aβ42/40 ratio well below reference"},
        "imaging": {"hippocampalVolumeCm3": 1.8, "note": "<2nd percentile for age"},
        "pet": {"amyloid": "Positive", "tau": "Positive", "note": "Consistent with AD pathology"},
        "score": 0.95,
        "stage": 4,
        "factors": [
            {"text": "Low hippocampal volume (1.8 cm³, <2nd pct)", "effect": 0.21},
            {"text": "Markedly elevated p-tau181 (6.1 pg/mL)", "effect": 0.17},
            {"text": "MoCA declined 5 points in 6 months", "effect": 0.15},
            {"text": "Amyloid-positive PET", "effect": 0.12},
            {"text": "Age 79", "effect": 0.08},
            {"text": "Higher education (9 yrs)", "effect": -0.04},
        ],
        "updated_at": "2026-08-21 18:48",
        "history": [
            {"at": "2026-08-21 18:48", "text": "PET positive (amyloid + tau) → pipeline complete, specialist review"},
            {"at": "2026-08-14 13:10", "text": "MRI shows severe volume loss → advanced to Stage 3"},
        ],
    },
    {
        "id": "PTID-1204",
        "age": 71,
        "sex": "M",
        "education_years": 13,
        "family_history": True,
        "comorbidities": [],
        "cognitive": {"scale": "MoCA", "latest": 26, "prior": 27, "months": 6},
        "blood": None,
        "imaging": None,
        "pet": None,
        "score": 0.29,
        "stage": 1,
        "factors": [
            {"text": "Family history of dementia", "effect": 0.09},
            {"text": "Age 71", "effect": 0.05},
            {"text": "Higher education (13 yrs)", "effect": -0.11},
            {"text": "MoCA stable (26–27) over 6 months", "effect": -0.07},
        ],
        "updated_at": "2026-08-18 10:03",
        "history": [
            {"at": "2026-08-18 10:03", "text": "Risk-scored 0.29 → prioritized Low at Stage 1"},
        ],
    },
]