"""Patient store.

Preference order:    1. Synthetic ADNI-shaped cohort: data/processed/synthetic_patients.json
     (when present; generated by scripts/generate_adni_like.py)
  2. Real OASIS scores: data/processed/risk_scores.json (written by scripts/train_model.py)
  3. Mock cohort (backend/app/seed_data.py) so the API demos standalone

Real OASIS-1 has no blood/MRI/PET results, so those slots stay empty and every
subject starts at Stage 1 -- the escalation engine recommends the next test from
their risk tier exactly as it would for a patient entering the pipeline.
"""
from __future__ import annotations

import copy
import csv
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from .config import GLOBAL_IMPORTANCE_PATH, RISK_SCORES_PATH, PROJECT_ROOT, risk_tier
from .seed_data import MOCK_PATIENTS

# Feature name -> human-readable explanation (blueprint section 4.4)
HUMAN_FEATURES = {
    "mmse": "Latest MMSE score",
    "age": "Age",
    "education_years": "Education (years)",
    "ses": "Socioeconomic status (SES)",
    "etiv": "Intracranial volume (eTIV)",
    "nwbv": "Normalized whole-brain volume (nWBV)",
    "asf": "Atlas scaling factor (ASF)",
    "sex": "Sex",
    "mmse_change": "MMSE change vs first visit",
    "n_visits": "Number of recorded visits",
    "study_years": "Years in study",
    "ptau181": "p-tau181 (blood biomarker)",
    "abeta4240": "Aβ42/40 ratio (blood biomarker)",
    "hippocampal_volume": "Hippocampal volume (MRI)",
    "amyloid_positive": "Amyloid PET status",
    "tau_positive": "Tau PET status",
}

NOW = datetime.now().strftime("%Y-%m-%d %H:%M")

# Static global importances used in mock mode (mirror of the frontend panel).
MOCK_GLOBAL_IMPORTANCE = [
    {"feature": "MoCA / MMSE decline (6 mo)", "mean_abs_shap": 0.24},
    {"feature": "p-tau181 (blood)", "mean_abs_shap": 0.19},
    {"feature": "Hippocampal volume (MRI)", "mean_abs_shap": 0.16},
    {"feature": "Age", "mean_abs_shap": 0.12},
    {"feature": "Aβ42/40 ratio (blood)", "mean_abs_shap": 0.09},
    {"feature": "Education (years)", "mean_abs_shap": 0.07},
    {"feature": "Hypertension", "mean_abs_shap": 0.05},
    {"feature": "Type 2 diabetes", "mean_abs_shap": 0.04},
    {"feature": "Family history", "mean_abs_shap": 0.03},
]


def _map_real_record(r: dict) -> dict:
    """risk_scores.json entry -> internal patient record."""
    score = float(r.get("risk_score", 0.5))
    tier = risk_tier(score)
    mmse = r.get("mmse")
    factors = []
    for f in r.get("top_factors", []):
        feature = f.get("feature", "")
        factors.append(
            {
                "feature": feature,
                "text": HUMAN_FEATURES.get(feature, feature),
                "value": f.get("value"),
                "effect": float(f.get("contribution", 0.0)),
            }
        )
    return {
        "id": str(r.get("subject_id")),
        "age": r.get("age"),
        "sex": r.get("sex"),
        "education_years": r.get("education_years"),
        "family_history": False,
        "comorbidities": [],
        "cognitive": {"scale": "MMSE", "latest": mmse, "prior": mmse, "months": 6} if mmse is not None else None,
        "blood": None,
        "imaging": None,
        "pet": None,
        "score": score,
        "stage": 1,
        "factors": factors,
        "updated_at": NOW,
        "history": [
            {
                "at": NOW,
                "text": f"Scored {score:.2f} → prioritized {tier} at Stage 1 (latest OASIS visit)",
            }
        ],
    }


def _synthetic_records(rows: list[dict]) -> list[dict]:
    """Synthetic cohort records are already in the internal API shape.

    Scores and per-patient factors are recomputed from the SERVED model
    (artifacts/pipeline.joblib) in one vectorized batch pass at startup, so the
    dashboard always reflects the actual trained classifier -- including every
    feature's SHAP contribution (not just a top-3 cut). Falls back to the
    generator's heuristic scores when no model artifact exists.
    """
    records = [copy.deepcopy(r) for r in rows]
    try:
        from . import model_service

        if model_service.available():
            feature_rows = [model_service.record_to_features(rec) for rec in records]
            results = model_service.score_batch(feature_rows)
            scored = 0
            for rec, res in zip(records, results):
                if res is None:
                    continue
                rec["score"] = res["score"]
                rec["factors"] = [
                    {
                        "feature": f["feature"],
                        "text": HUMAN_FEATURES.get(f["feature"], f["feature"]),
                        "value": f["value"],
                        "effect": float(f["contribution"]),
                    }
                    for f in res["factors"]
                ]
                scored += 1
            print(f"[storage] re-scored {scored}/{len(records)} records from the served model")
            return records
    except Exception as exc:  # noqa: BLE001 -- fall back to generator scores
        print(f"[storage] model batch rescore failed ({exc}); keeping generator scores")

    # Fallback: generator's heuristic scores with whatever factors the file has
    try:
        if RISK_SCORES_PATH.exists():
            model_scores = json.loads(RISK_SCORES_PATH.read_text(encoding="utf-8"))
            by_id = {str(m.get("subject_id")): m for m in model_scores}
            overlaid = 0
            for rec in records:
                m = by_id.get(str(rec.get("id")))
                if not m:
                    continue
                rec["score"] = float(m.get("risk_score", rec.get("score", 0.5)))
                rec["factors"] = [
                    {
                        "feature": f.get("feature"),
                        "text": HUMAN_FEATURES.get(f.get("feature"), f.get("feature")),
                        "value": f.get("value"),
                        "effect": float(f.get("contribution", 0.0)),
                    }
                    for f in m.get("top_factors", [])
                ]
                overlaid += 1
            if overlaid:
                print(f"[storage] overlaid risk_scores.json onto {overlaid} records (fallback path)")
    except Exception as exc:  # noqa: BLE001
        print(f"[storage] could not overlay model scores ({exc})")
    return records


def _file_records() -> tuple[list[dict], str]:
    """Records from the real OASIS scores when present, else the mock cohort."""
    from os import getenv

    # v2 = ADNI-1-proportioned cohort (800 subjects, all stages populated)
    synthetic_path = PROJECT_ROOT / "data" / "processed" / "synthetic_patients_v2.json"
    if not synthetic_path.exists():
        synthetic_path = PROJECT_ROOT / "data" / "processed" / "synthetic_patients.json"

    # Prefer the synthetic cohort when present and the user has not opted into real data.
    data_mode = os.getenv("OASIS_DATA_MODE", "").strip().lower()
    if data_mode not in {"real", "1", "true"} and synthetic_path.exists():
        try:
            raw = json.loads(synthetic_path.read_text(encoding="utf-8"))
            if isinstance(raw, list) and raw:
                return _synthetic_records(raw), "synthetic"
        except Exception as exc:  # noqa: BLE001
            print(f"[storage] could not load {synthetic_path} ({exc}); falling back to real/mock")

    if RISK_SCORES_PATH.exists():
        try:
            raw = json.loads(RISK_SCORES_PATH.read_text(encoding="utf-8"))
            return [_map_real_record(r) for r in raw], "real"
        except Exception as exc:  # noqa: BLE001 -- bad/missing file should not crash the API
            print(f"[storage] could not load {RISK_SCORES_PATH} ({exc}); falling back to mock data")

    return [copy.deepcopy(p) for p in MOCK_PATIENTS], "mock"


def load_patients() -> tuple[dict[str, dict], str]:
    """Return (id -> record, data_source).

    When DATABASE_URL is set, Postgres is seeded from the same source and becomes
    the store of record (memory stays the read cache). Otherwise in-memory only.
    """
    records, source = _file_records()
    from . import db
    if db.enabled():
        print("[storage] DATABASE_URL detected — initializing database store...")
    else:
        print("[storage] DATABASE_URL not set — using in-memory store (no persistence)")
    if db.enabled():
        try:
            db.init_db()
            db.seed_if_empty(records)
            loaded = db.load_all()
            if loaded:
                db_name = "sqlite" if (db.get_database_url() or "").startswith("sqlite") else "postgres"
                return {r["id"]: r for r in loaded}, f"{source}+{db_name}"
        except Exception as exc:  # noqa: BLE001 -- DB down should not crash the API
            print(f"[storage] Database unavailable ({exc}); using in-memory store")
    return {r["id"]: r for r in records}, source


def persist(record: dict) -> None:
    """Mirror a mutation (stage advance) to DB. Best-effort; never raises."""
    from . import db
    if not db.enabled():
        return
    try:
        db.save_record(record)
    except Exception as exc:  # noqa: BLE001
        print(f"[storage] could not persist {record['id']} to DB ({exc})")


def load_global_importance() -> list[dict]:
    """Prefer artifacts/global_importance.csv (real training run), else the static mock."""
    if GLOBAL_IMPORTANCE_PATH.exists():
        try:
            rows = []
            with GLOBAL_IMPORTANCE_PATH.open(encoding="utf-8", newline="") as fh:
                for row in csv.DictReader(fh):
                    rows.append(
                        {
                            "feature": row.get("feature", ""),
                            "mean_abs_shap": float(row.get("mean_abs_shap", 0.0)),
                        }
                    )
            if rows:
                return rows
        except Exception as exc:  # noqa: BLE001
            print(f"[storage] could not parse {GLOBAL_IMPORTANCE_PATH} ({exc}); using static list")
    return copy.deepcopy(MOCK_GLOBAL_IMPORTANCE)


# Repo root, exposed for tests/scripts that need to reference processed data
ROOT = PROJECT_ROOT